# Generated by Django 4.2.2 on 2023-11-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('desc', models.TextField(max_length=250)),
            ],
            options={
                'db_table': 'bankdb',
            },
        ),
    ]
