# Generated by Django 4.2.2 on 2023-11-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank',
            table='bank',
        ),
    ]
