# Generated by Django 4.2.2 on 2023-11-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_bank_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank',
            table='bankdb',
        ),
    ]
