# Generated by Django 4.2.2 on 2023-11-01 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_bank_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.bank')),
            ],
        ),
    ]
