# Generated by Django 4.2.2 on 2023-11-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_branch_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_desc',
            name='name',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='branch_desc',
        ),
    ]
