# Generated by Django 4.2.2 on 2023-11-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_alter_bank_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
