# Generated by Django 4.2.2 on 2023-11-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
