# Generated by Django 4.2.2 on 2023-11-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_remove_bank_id_alter_bank_desc_alter_bank_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
