# Generated by Django 4.2.2 on 2023-11-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
