# Generated by Django 4.2.2 on 2023-11-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
